/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type { VestingHelper, VestingHelperInterface } from "../VestingHelper";

const _abi = [
  {
    inputs: [],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    inputs: [
      {
        internalType: "address[]",
        name: "vestingContracts",
        type: "address[]",
      },
    ],
    name: "getBeneficiaries",
    outputs: [
      {
        internalType: "address[]",
        name: "",
        type: "address[]",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class VestingHelper__factory {
  static readonly abi = _abi;
  static createInterface(): VestingHelperInterface {
    return new utils.Interface(_abi) as VestingHelperInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): VestingHelper {
    return new Contract(address, _abi, signerOrProvider) as VestingHelper;
  }
}
